### ISSUE TITLE
Parser - [@search] is an unknown property

### ISSUE THREAD

**Issue by stefanszasz** [getMoreBrain/bitmark-parser-generator#147]
Parsing a bit with `@search:..` returns parser warning:

```
[.video]
[@id:305047]
[&video:https://docs.getmorebrain.com/bit-books/swiss_life_select/imge.png]
[@search:Errungenschaftsbeteiligung, Scheidung, Güterrechtliche Auseinandersetzung, Vorschlag]
```

I think this is a standard property that parser should support without warnings. @gaba-getmorebrain

**Comment by gaba-getmorebrain** [comment]
@stefanszasz Yes, correct. It's a single trimmed string.
@zx-ncoderz

**Comment by zx-ncoderz** [comment]
https://github.com/getMoreBrain/bitmark-parser-generator/releases/tag/v1.5.17

**Comment by gaba-getmorebrain** [comment]
@stefanszasz Can you please test and close?
