### ISSUE TITLE
Parser: Add [.extractor-repeated-text], [.extractor-page-number]

### ISSUE THREAD

**Issue by six5536** [getMoreBrain/bitmark-parser-generator#148]

**Comment by gaba-getmorebrain** [comment]
This does not seem to be supported yet by the parser.

**Comment by six5536** [comment]
Released in https://github.com/getMoreBrain/bitmark-parser-generator/releases/tag/v1.5.21

**Comment by gaba-getmorebrain** [comment]
@stefanszasz It looks like the deployments of Richard (@six5536 ) do not get thru.
I can see that it is triggering a deployment on Slack, but the new versions don't arrive on cosmic.
Can you please check?





![Image](https://github.com/getMoreBrain/bitmark-parser-generator/assets/40243242/67f1c3b4-4456-4fb4-8a0b-d6456c5180c3)

**Comment by stefanszasz** [comment]
@gaba-getmorebrain Yes, there is a bug in the CircleCI pipeline and it does not deploy correctly the latest package when being triggered from Richard on a new package deploy. Rolling it out now

**Comment by stefanszasz** [comment]
@gaba-getmorebrain parser updated and deployed to cosmic

**Comment by gaba-getmorebrain** [comment]
@stefanszasz Seems to work only 50%.
When I use the bitmark Editor, it works. When I try to save. I get an error.
Looks like the editor and saving are using two different parsers.
Or saving is more strict.

<img width="1624" alt="image" src="https://github.com/getMoreBrain/bitmark-parser-generator/assets/40243242/29babb79-9952-40bd-83df-88256aee72a1">

**Comment by gaba-getmorebrain** [comment]
<img width="1624" alt="image" src="https://github.com/getMoreBrain/bitmark-parser-generator/assets/40243242/4312c50a-0b3b-46a3-82aa-b9d721c7716f">

**Comment by stefanszasz** [comment]
@gaba-getmorebrain yes, the mismatched version was the problem. Doing a proper install of the latest version did not work in the bitmark-api for reasons I have not determined yet and which I will find tomorrow. But I explicitly bumped the version and redeployed to cosmic (and deployed to prod now as well)

**Comment by gaba-getmorebrain** [comment]
@stefanszasz Thanks a lot!
