### ISSUE TITLE
Render and Brand: Create [.extractor-...] bits

### ISSUE THREAD

**Issue by six5536** [getMoreBrain/bitmark-parser-generator#159]
Render and Style:

- extractor-page (I think, this one is done)
- extractor-page-with-blocks (same as extractor-page including the popup menu, if it has the classification properties)
- extractor-block  (same as extractor-page including the popup menu, if it has the classification properties)
- extractor-repeated-text (same as .article)
- extractor-page-number (same as .article)
- extractor-page-header (same as .article)
- extractor-page-footer (same as .article)

**Comment by six5536** [comment]
Released in https://github.com/getMoreBrain/bitmark-parser-generator/releases/tag/v1.5.21

**Comment by gaba-getmorebrain** [comment]
@alexmoraru25

**Comment by gaba-getmorebrain** [comment]
@six5536 How was this story created? It got a real low id and it is kind of from hell: I get random messages that I don't have access and I cannot assign Alex to it. I could not assign it the the Get More Brain project for a half an hour. Now it works. However, I can still not assign Alex.
