### ISSUE TITLE
Parsing a comment bit does not return ids

### ISSUE THREAD

**Issue by stefanszasz** [getMoreBrain/bitmark-parser-generator#164]
For a comment bit:

```
[.|pageNumber]
[@id:946897]
5
```

Parsed JSON:

```
[
    {
        "bit": {
            "type": "_comment"
        },
        "parser": {
            "version": "1.5.22",
            "bitmarkVersion": "2",
            "textParserVersion": "8.10.3",
            "commentedBitType": "[.pageNumber]"
        },
        "bitmark": "[.|pageNumber]\n[@id:946897]\n5"
    }
]
```

There is no `.id` in the parsed bit JSON. The ids are essential when we publish the same book.

**Comment by gaba-getmorebrain** [comment]
@six5536 It would be great as well to add a property for the commented out bit type.
"commentedOutBitType": "pageNumber"

**Comment by six5536** [comment]
> @six5536 It would be great as well to add a property for the commented out bit type. "commentedOutBitType": "pageNumber"

@gaba-getmorebrain this already exists in the parser section.

**Comment by six5536** [comment]
@gaba-getmorebrain I think a good solution here is to parser the comment bits as normal, but just:

1. Replace the bit type with `"type": "_comment"`
2. Add `"commentedBitType": "[.pageNumber]"` to the `parser` section

**Comment by six5536** [comment]
```
[.|article]
[@id:12353456]

This is the table caption
```

<==>

```json
[
  {
    "bit": {
      "type": "_comment",
      "commentedType": "article",
      "id": [
        "12353456"
      ],
      "body": [
        {
          "type": "paragraph",
          "content": [
            {
              "text": "This is the table caption",
              "type": "text"
            }
          ],
          "attrs": {}
        }
      ]
    },
    "parser": {
      "version": "1.5.23",
      "bitmarkVersion": "3",
      "textParserVersion": "8.10.3"
    },
    "bitmark": "[.|article]\n[@id:12353456]\n\nThis is the table caption"
  }
]
```

**Comment by six5536** [comment]
Released in https://github.com/getMoreBrain/bitmark-parser-generator/releases/tag/v1.5.23

**Comment by gaba-getmorebrain** [comment]
FYI @stefanszasz
