### ISSUE TITLE
Parser / Text Parser: Breakscaping, incorrect edge cases

### ISSUE THREAD

**Issue by six5536** [getMoreBrain/bitmark-parser-generator#264]
```
[.article]
*^*Text*^*   
<OK - [`**Text**`]>

[.article]
***Text**
<OK - [bold `*Text`]>

[.article]
***Text***
<OK - [bold `*Text`, `*`]>

[.article]
*^**Text*^**
<ERROR - should be [`*`, bold `Text*`] ???, is [`*^`, bold `Text*^`]>

[.article]
***Text*^**
<ERROR - should be [bold `*Text*`] ???, is [bold `*Text*^`]>
```

Two bitmark text edge cases are shown above that do not convert to JSON correctly. 

The problem is in the breakscaping.

In the first error case, the following strings are 'unbreakscaped'
`*^`
`Text*^`

In the second error case, the following strings are 'unbreakscaped'
`*Text*^`

In all cases, the problem is that `*^` is not recognised as a case that needs unbreakscaping.

The reason this is occurring is because not ALL `^` are treated as a breakscape. Only `^` in certain positions are treated as breakscaping (e.g. `^]`, `[^.`, `*^*` , `_^_` , etc.)

There are 2 options:
1. Go back to treating ALL `^` as a breakscape, so if you want to add an `^` you HAVE to add `^^` anywhere in bitmark. This will cause some issues for `[.code]` and inline code as it often contains `^`. Another issue will be ids that contain `^`. These issues are nasty.
2. Handle the edge cases where the string being breakscaped is split immediately after a breakscaping `^`. In this case, the issues in 1 can still occur occasionally, and it is not necessarily clear to the bitmark writer when breakscaping is required.

In the case of `2.` the new matches for breakscaping would be:
`=^`
`*^`
`<tick>^`
`_^`
`!^`
`[^`

That would mean any string that literally contains `=^` (etc) would need to be written as `=^^`, but most `^` would be able to be written as is.

---

Both solutions have serious drawbacks, so I'd like to discuss them at the weekly meeting
@gaba-getmorebrain

**Comment by gaba-getmorebrain** [comment]
@six5536 Actually, I think, this is solved.
The bitmark standard uses option 1.
We usually do not use bitmark-- (or ++) for .code. We use the text format "text", which is just plain text and does not have/need any breakscaping. 
Let's discus tomorrow.

**Comment by six5536** [comment]
```
[.article:code]
[@id:48569023^^$%243^]^]]
[@instruction:This has a ^] bracket in it]

====
$$ x^2 
[.article]

$$
```

**Comment by gaba-getmorebrain** [comment]
@six5536 If we use $$, we actually would not need ====

```
[.formula:latex]
[@id:48569023^^$%243^]^]]
[@instruction:This has a ^] bracket in it]

$$ x^2 
[.article]

$$
```
As bitmark is streamable, the above solution does not work. The stream could start with `x^2 
[.article]`

We need to go like this:

```
[.formula:latex]
[@id:48569023^^$%243^]^]]
[@instruction:This has a ^] bracket in it]

====
 x^2 
[^.article]

[.article]

```

We still need to breaksacpe `[.` at the beginning of a line.

However, I am not sure, if `[.article]` at the beginning of a line could even exist in latex. 

... may be not in formualas, however, easily in LaTeX ducoments:

![Image](https://github.com/user-attachments/assets/1de13323-5ba2-4cce-b712-8803a114b595)

**Comment by gaba-getmorebrain** [comment]
@six5536 I suggest, for text or other code formats, we use the ==== or a $$$$ separator (if this makes it more easy for you and we breakscape only `[.` at the beginning of a line.

```
[.formula:latex]
[@id:48569023^^$%243^]^]]
[@instruction:This has a ^] bracket in it]

$$$$
 x^2 
[^.article]

[.article]
This is the next bit already
```

**Comment by gaba-getmorebrain** [comment]
I will then use $$ x^2  $$ for inline formulas in LaTeX.

**Comment by six5536** [comment]
> @six5536 I suggest, for text or other code formats, we use the ==== or a $$$$ separator (if this makes it more easy for you and we breakscape only `[.` at the beginning of a line.
> 
> ```
> [.formula:latex]
> [@id:48569023^^$%243^]^]]
> [@instruction:This has a ^] bracket in it]
> 
> $$$$
>  x^2 
> [^.article]
> 
> [.article]
> This is the next bit already
> ```

@gaba-getmorebrain 
Looks good.

For inline latex, $$ $$ is great.

For bit level formulae, I am not sure we even need a separator. I will know these bits are not bitmark--/bitmark++ as they will be marked :latex or :text or similar, or will default to such. In this case the start of the text can be assumed to be the first text that is not whitespace and not a valid bitmark tag. I have included such in the examples below.

That would mean, final spec:

Inline LaTeX
```
[.article]
This ($$ \(E=mc^2\) $$) is some inline LaTeX
This ($^$ \(E=mc^2\) $^$) is NOT inline LaTeX as it is breakscaped
```

Preformatted text
```
[.article:text]
[!instruction:blah]
Here is some preformatted text. **bold** and $$ LaTeX $$ will be rendered as is, and not interpreted in any way.

[.code]
[!instruction:blah]

Here is some preformatted text, which would usually be some code.
[!instruction:this instruction will not be interpreted as it is after the start of the preformatted code]
This is preformatted because this bit defaults to :text.
The only thing that needs to be escaped is [. at the beginning of a line as shown below.
[^.code]
This is still part of the above preformatted section belonging to the [.code] bit

[.formula:latex]
[!instruction:what follows is preformatted as :latex has the same parsing rules as :text]
 \(E=mc^2\)


```

**Comment by gaba-getmorebrain** [comment]
@six5536 Shouldn't there be separators like this:

Preformatted text
```
[.article:text]
[!instruction:blah]
Here is some preformatted text. **bold** and $$ LaTeX $$ will be rendered as is, and not interpreted in any way.

[.code]
[!instruction:blah]

$$$$
Here is some preformatted text, which would usually be some code.
[!instruction:this instruction will not be interpreted as it is after the start of the preformatted code]
This is preformatted because this bit defaults to :text.
The only thing that needs to be escaped is [. at the beginning of a line as shown below.
[^.code]
This is still part of the above preformatted section belonging to the [.code] bit

[.formula:latex]
[!instruction:what follows is preformatted as :latex has the same parsing rules as :text]
$$$$
 \(E=mc^2\)


```

**Comment by six5536** [comment]
Released in https://github.com/getMoreBrain/bitmark-parser-generator/releases/tag/v1.35.0
