### ISSUE TITLE
Add support for @subtype: tag in the book bit

### ISSUE THREAD

**Issue by stefanszasz** [getMoreBrain/bitmark-parser-generator#27]
**Is your feature request related to a problem? Please describe.**

Some books/notebooks can have subtypes - this is used to differentiate between different notebooks, for example. We have regular notebooks that a user creates manually and notebooks that are generated through PDF conversion - for these, we set `@subtype:pdf`

Would like the parser to support for`@subtype:` with the following values:
```
draft-book
flashcard
learning-path
pdf
worksheet
```

Example: 
```
[.book]
[#Some book]
[@publisher:a-pub-int]
[@subtype:pdf]
[##Subtitle]

```

Currently, v1.0.9 parser returns a warning when it encounters this `"message": "'Property' with key 'subtype' is an unexpected property. It is not included in the output by default".

@gaba-getmorebrain FYI

**Comment by zx-ncoderz** [comment]
@stefanszasz @gaba-getmorebrain 
See issue #31 

This looks like it is a well defined property of the book rather than a standard extra property.
I will add it as such.

**Comment by zx-ncoderz** [comment]
@stefanszasz @gaba-getmorebrain  I have some questions
1. Does @subtype only apply to the .book bit?
2. @publisher currently returns an array (i.e. there can be more than one @publisher tag) - is this the wanted behaviour?

Thanks.

**Comment by zx-ncoderz** [comment]
TODO:
- Replace `includeExtraProperties` with the inverse `excludeExtraProperties`
- Move parser extra property warnings under 'verbose' option

**Comment by zx-ncoderz** [comment]
Released in https://github.com/getMoreBrain/bitmark-parser-generator/releases/tag/v1.0.11
