### ISSUE TITLE
Properties should be trimmed? @example, @Date, @bot, @Level

### ISSUE THREAD

**Issue by zx-ncoderz** [getMoreBrain/bitmark-parser-generator#75]
@example, @Date, @bot, @level are currently non-trimmed property strings.
I think probably @example is correct and the others should actually be trimmed.

@gaba-getmorebrain please confirm.

**Comment by gaba-getmorebrain** [comment]
@zx-ncoderz They should all be trimmed. Including @example

**Comment by zx-ncoderz** [comment]
Released in https://github.com/getMoreBrain/bitmark-parser-generator/releases/tag/v1.4.6
