### ISSUE TITLE
Parser: Bug: [@kind] not recognised for [.book]

### ISSUE THREAD

**Issue by zx-ncoderz** [getMoreBrain/bitmark-parser-generator#78]
There seems to be a breaking change in the latest version of the parser affecting .book.type property:

[.book]
[@kind:learning-path]
[#LP]

In the past this used to return the JSON parsed book.type=“learning-path value.

Did you remove this intentionally? Because now I just get “type=book”.

...

Just did a review now, this is what the parser returns - “_kind" has a underscore prefix

![Image](https://github.com/getMoreBrain/bitmark-parser-generator/assets/10079653/60346c05-56cd-45e9-b261-e0ba9b493daf)

In the previous version, it was fine:

        "bit": {
            "type": "book",
            "format": "bitmark--",
            "kind": "learning-path",
            "title": "LP",
            "item": "",
            "hint": "",
            "isExample": false,
            "example": null,
            "body": ""
        },

**Comment by zx-ncoderz** [comment]
@gaba-getmorebrain @stefanszasz 

This bug occurred because I made a mistake that caused the 'kind' to have an undescore because the parser thought there was a clash with another property when there was not.

However, it highlighted the issue that the @kind property was not assigned to [.book] bit, so it was considered an extra property and was generating a warning.

I also have the following properties that are not assigned to any bits. 
Please can you let me know which bits need these properties, or if they are completely legacy and can be removed:

[@publications]
[@thumbImage]
[@bot] <= [.learning-path-bot-training] I believe
[@reference]
[@partialAnswer]
[@toc]
[@progress]
[@level]
[@type]

**Comment by zx-ncoderz** [comment]
Released in https://github.com/getMoreBrain/bitmark-parser-generator/releases/tag/v1.4.3

**Comment by gaba-getmorebrain** [comment]
cc @stefanszasz
